version: '3.8'

services:
  backend:
    build: ./backend
    network_mode: "host"  # Добавьте эту строку
    environment:
      - NODE_ENV=development
      - CHROME_ENDPOINT=${CHROME_ENDPOINT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - VIDEO_LIMIT=${VIDEO_LIMIT:-10}
      - COMMENT_LIMIT=${COMMENT_LIMIT:-20}
      - PORT=3001
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./data:/app/data

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - scraper-network

networks:
  scraper-network:
    driver: bridge